Repository ReCoderTeam/ReCoder_SubProject, pull requests merged in 2024-12, with the labels that each got.

#135 24/12/10 [ 결제신청 상신기능작업]
  reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dto/ApprovalRequestDTO.java
  reFactorial/src/main/resources/static/css/approval/approvalMain.css
  reFactorial/src/main/resources/static/css/approval/approvalPage.css
  reFactorial/src/main/resources/static/css/approval/searchEmployee.css
  reFactorial/src/main/resources/static/css/approval/searchReferrers.css
  reFactorial/src/main/resources/templates/approvals/approvalMain.html
  reFactorial/src/main/resources/templates/approvals/approvalPage.html
  reFactorial/src/main/resources/templates/approvals/referenceDocs.html
  reFactorial/src/main/resources/templates/approvals/searchEmployee.html
  reFactorial/src/main/resources/templates/approvals/searchReferrers.html
Labels: 🏗️최적화 작업🚧

#134 Feature/121_ board_regist_wook
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java
  reFactorial/src/main/resources/mappers/board/BoardMapper.xml
  reFactorial/src/main/resources/templates/board/freeBoard.html
  reFactorial/src/main/resources/templates/board/postDetail.html
  reFactorial/src/main/resources/templates/board/postUpdate.html
Labels: ☑️일거리 등록☑️

#147 Feature/1210_board_crud_wook
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/config/SecurityConfig.java
  reFactorial/src/main/resources/mappers/board/BoardMapper.xml
  reFactorial/src/main/resources/templates/board/document.html
  reFactorial/src/main/resources/templates/board/event.html
  reFactorial/src/main/resources/templates/board/freeBoardRegist.html
  reFactorial/src/main/resources/templates/board/list.html
  reFactorial/src/main/resources/templates/board/notification.html
  reFactorial/src/main/resources/templates/board/postDetail.html
  reFactorial/src/main/resources/templates/board/postUpdate.html
  reFactorial/src/main/resources/templates/board/sharedWork.html
  reFactorial/src/main/resources/templates/board/sidebar.html
  reFactorial/src/main/resources/templates/board/vote.html
  reFactorial/src/main/resources/templates/common/header.html
Labels: ☑️일거리 등록☑️

#162 Feature/1213_board_vote_regist [투표기능]
  reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java
  reFactorial/src/main/resources/static/css/board/freeBoardRegist.css
  reFactorial/src/main/resources/templates/board/freeBoardRegist.html
  reFactorial/src/main/resources/templates/board/postDetail.html
Labels: ☑️일거리 등록☑️

#168 Feature/241212 chan 회의실 백엔드 작업
  .idea/12_first-project.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/CabinetController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/CabinetDAO.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/ReservationDAO.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dto/CabinetDTO.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/CabinetService.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/controller/MailController.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/model/dto/MailDTO.java
  reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/service/MailService.java
  reFactorial/src/main/resources/mappers/booking/CabinetMapper.xml
  reFactorial/src/main/resources/mappers/booking/ReservationMapper.xml
  reFactorial/src/main/resources/templates/booking/booking.html
  reFactorial/src/main/resources/templates/booking/bookingList.html
  reFactorial/src/main/resources/templates/common/header.html
  reFactorial/src/main/resources/templates/mail/mailMain.html
  reFactorial/src/main/resources/templates/mail/writeMail.html
Labels: Issue🌠
